"""Adding admin flag to the users table

Revision ID: 24423cf98409
Revises: ac61297aa105
Create Date: 2026-04-09 09:38:10.886190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24423cf98409'
down_revision = 'ac61297aa105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
