"""Updated tasks.created_by to be a mandatory param

Revision ID: ac61297aa105
Revises: 33b209e32560
Create Date: 2026-03-19 10:06:10.052729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac61297aa105'
down_revision = '33b209e32560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
